### ISSUE TITLE
Add option to render part of the diff (without the header)

### ISSUE THREAD

**Issue by EncodePanda** [chrissound/GitChapter#3]
When

```diff
{{ gitDiff package.yaml }}
```

Now:

```
diff --git a/package.yaml b/package.yaml
index 2d9a1e9..37b4b54 100644
--- a/package.yaml
+++ b/package.yaml
@@ -14,6 +14,7 @@ description:         Please see the README on GitHub at 

 dependencies:
 - base >= 4.7 && < 5
+- aeson
 
 library:
   source-dirs: src
```

What I hope to have

```
 dependencies:
 - base >= 4.7 && < 5
+- aeson
 
 library:
   source-dirs: src
```

This could be some sort of option that you have to turn on so that the project stays backward compatible.

Happy to help, please point me to places :)
